const fs = require('fs');
const NL = String.fromCharCode(10);
const p = '/var/www/bermuda-epass/index.html';
let s = fs.readFileSync(p, 'utf8');
if (s.includes('hotspotSection')) { console.log('ALREADY_PATCHED'); process.exit(0); }
const html = [
'<div id="hotspotSection" style="padding:0 0 16px;">',
'  <div style="padding:16px 16px 8px;display:flex;align-items:center;justify-content:space-between;">',
'    <div><h3 style="font-size:17px;font-weight:800;color:#0D1F2D;margin:0;">&#128293; HOT NOW in Bermuda</h3><p id="hotspotSub" style="font-size:11px;color:#6B7B84;margin:2px 0 0;">Live island pulse — updated by the hour</p></div>',
'    <span style="background:#FF3B30;color:#fff;font-size:9px;font-weight:800;padding:4px 8px;border-radius:20px;animation:hotPulse 1.6s infinite;">LIVE</span>',
'  </div>',
'  <div id="hotspot-map" style="height:300px;width:100%;"></div>',
'  <div id="hotspotList" style="display:flex;gap:8px;overflow-x:auto;padding:12px 16px 4px;scrollbar-width:none;"></div>',
'</div>',
'<div style="margin:0 16px 16px;background:linear-gradient(135deg,#0D1F2D,#1A3344);border-radius:20px;padding:16px;">',
'  <div style="color:#C9A84C;font-size:10px;font-weight:800;letter-spacing:2px;margin-bottom:10px;">THE EMPIRE NETWORK</div>',
'  <div style="display:flex;flex-direction:column;gap:8px;">',
'    <a href="https://bermudaobserver.com" target="_blank" style="display:flex;align-items:center;gap:10px;background:rgba(255,255,255,0.05);border-radius:12px;padding:10px 12px;text-decoration:none;"><span style="font-size:20px;">&#128240;</span><span style="flex:1;color:#fff;font-size:13px;font-weight:600;">Bermuda Observer — Island News</span><span style="color:#6B7B84;">›</span></a>',
'    <a href="https://bermudalocals.com" target="_blank" style="display:flex;align-items:center;gap:10px;background:rgba(255,255,255,0.05);border-radius:12px;padding:10px 12px;text-decoration:none;"><span style="font-size:20px;">&#128717;</span><span style="flex:1;color:#fff;font-size:13px;font-weight:600;">Bermuda Locals — Shop Small Businesses</span><span style="color:#6B7B84;">›</span></a>',
'    <a href="https://nvme.live" target="_blank" style="display:flex;align-items:center;gap:10px;background:rgba(255,255,255,0.05);border-radius:12px;padding:10px 12px;text-decoration:none;"><span style="font-size:20px;">&#127916;</span><span style="flex:1;color:#fff;font-size:13px;font-weight:600;">NVME.LIVE — Share Your Bermuda Clips</span><span style="color:#6B7B84;">›</span></a>',
'  </div>',
'</div>',
'<style>@keyframes hotPulse{0%,100%{opacity:1}50%{opacity:.5}} .hot-pin{position:relative} .hot-pin::after{content:"";position:absolute;inset:-8px;border-radius:50%;border:2px solid #FF3B30;animation:pinPing 1.5s ease-out infinite} @keyframes pinPing{from{transform:scale(.6);opacity:.9}to{transform:scale(1.8);opacity:0}} .hot-chip{flex-shrink:0;background:#fff;border-radius:14px;padding:10px 12px;box-shadow:0 2px 10px rgba(0,0,0,0.08);min-width:150px;cursor:pointer} .hot-chip:active{transform:scale(.96)}</style>',
'<script>',
'(function(){',
'  function bermudaHour(){ var d = new Date(); var utc = d.getTime() + d.getTimezoneOffset()*60000; return new Date(utc - 3*3600000).getHours(); }',
'  var SPOTS = [',
'    { name:"Horseshoe Bay", icon:"\uD83C\uDFD6\uFE0F", lat:32.2572, lng:-64.8317, hot:[9,17], tag:"Pink sand — best before 4pm" },',
'    { name:"Tobacco Bay", icon:"\uD83E\uDD3F", lat:32.3879, lng:-64.6769, hot:[10,16], tag:"Snorkel hotspot" },',
'    { name:"Crystal Caves", icon:"\uD83C\uDFE0", lat:32.3470, lng:-64.7130, hot:[9,17], tag:"Tours every 30 min" },',
'    { name:"Swizzle Inn", icon:"\uD83C\uDF79", lat:32.3490, lng:-64.7090, hot:[16,23], tag:"Happy hour energy" },',
'    { name:"Front Street Hamilton", icon:"\uD83D\uDED2", lat:32.2956, lng:-64.7820, hot:[10,22], tag:"Shops + harbour nights" },',
'    { name:"St. George\u2019s Town", icon:"\uD83C\uDFF0", lat:32.3807, lng:-64.6778, hot:[9,18], tag:"UNESCO old town" },',
'    { name:"Royal Naval Dockyard", icon:"\uD83D\uDEA2", lat:32.3165, lng:-64.8344, hot:[8,20], tag:"Cruise village + Clocktower" },',
'    { name:"Warwick Long Bay", icon:"\uD83C\uDF0A", lat:32.2570, lng:-64.8150, hot:[9,17], tag:"Quiet pink sand" },',
'    { name:"Elbow Beach", icon:"\uD83C\uDFD6\uFE0F", lat:32.2720, lng:-64.7760, hot:[9,17], tag:"Resort strip" },',
'    { name:"Black Horse Tavern", icon:"\uD83E\uDD9E", lat:32.3611, lng:-64.6500, hot:[12,21], tag:"Fish chowder HQ" }',
'  ];',
'  var h = bermudaHour();',
'  var live = SPOTS.map(function(sp){ var on = h >= sp.hot[0] && h < sp.hot[1]; return { sp: sp, on: on }; });',
'  var el = document.getElementById("hotspotList");',
'  if (el) {',
'    live.forEach(function(x){',
'      var c = document.createElement("div");',
'      c.className = "hot-chip";',
'      c.style.opacity = x.on ? "1" : "0.55";',
'      c.innerHTML = "<div style=\"font-size:11px;font-weight:800;color:#0D1F2D;\">"+x.sp.icon+" "+x.sp.name+"</div><div style=\"font-size:10px;color:#6B7B84;margin-top:2px;\">"+x.sp.tag+"</div><div style=\"font-size:9px;font-weight:800;margin-top:4px;color:"+(x.on?"#FF3B30":"#6B7B84")+";\">"+(x.on?"\u25CF HOT NOW":"\u25CB opens later")+"</div>";',
'      el.appendChild(c);',
'    });',
'  }',
'  function initHotMap(){',
'    if (typeof L === "undefined" || !document.getElementById("hotspot-map")) { return setTimeout(initHotMap, 500); }',
'    var m = L.map("hotspot-map", { zoomControl:false, attributionControl:false, scrollWheelZoom:false }).setView([32.300, -64.770], 11);',
'    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 18 }).addTo(m);',
'    live.forEach(function(x){',
'      var color = x.on ? "#FF3B30" : "#6B7B84";',
'      var ic = L.divIcon({ className: x.on ? "hot-pin" : "", html: "<div style=\"font-size:22px;filter:drop-shadow(0 2px 4px rgba(0,0,0,0.4));\">"+x.sp.icon+"</div>", iconSize:[28,28], iconAnchor:[14,14] });',
'      L.marker([x.sp.lat, x.sp.lng], { icon: ic }).addTo(m).bindPopup("<strong>"+x.sp.name+"</strong><br><span style=\"font-size:11px;color:"+color+";font-weight:700;\">"+(x.on?"HOT NOW":"Opens later")+"</span><br><span style=\"font-size:11px;\">"+x.sp.tag+"</span>");',
'    });',
'  }',
'  initHotMap();',
'})();',
'</scr' + 'ipt>',
'</body>'
].join(NL);
if (!s.includes('</body>')) { console.error('BODY_NOT_FOUND'); process.exit(1); }
s = s.replace('</body>', html);
fs.writeFileSync(p, s);
console.log('HOTSPOT_PATCHED');
